<<<<<<< HEAD
title: ""
=======
title: "Mathematical interpretation of leetcode problem"
>>>>>>> parent of ea1344a (Two sum problem)
description: "Work in progress.."
baseurl: "/leetcode"  # must match repo name
url: "https://ujjawal360.github.io"
permalink: pretty
markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Prevent Jekyll from processing these files
exclude:
  - node_modules
  - vendor

# Allow curly braces in markdown
liquid:
  error_mode: strict
